<?php
global $current_user;
global $step1;
global $step2;
global $step3;
global $profile_picture;
global $firstname;
global $lastname;
global $gender;
global $work_authorization;
global $age;
global $bday;
global $availability;
global $expertise;
global $contact;
global $email_address;
global $work_experiences;
global $skills;
global $languages;
global $certificates;

global $career_objective;
global $tertiary;
global $course;
global $linkedin;
global $desired_salary;
global $verification;
global $school_s_year;
global $school_e_year;

global $address;
global $nationality;
global $employment_status;

global $about_me;
?>